server:
  port: 52151

spring:
  cloud:
    mesh:
      sidecar:
        host: 127.0.0.1
        port: 12345
        service-id: sidecar-demo
      discovery:
        server-addr: http://localhost:52152
